apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: nginx-ingress
spec:
 rules:
   - host: nginx.k8s.yourdomain.ltd
     http:
       paths:
         - path: /
           backend:
             serviceName: nginx
             servicePort: 80
