apiVersion: v1
data:
  jenkins-admin-password: RldNYm1YZWJ3TjNuUFFs
  jenkins-admin-user: YWRtaW4=
kind: Secret
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: jenkins
type: Opaque

