apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    app: neo4j
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j:latest
        resources:
          requests:
            cpu: "500m"
            memory: "256Mi"
        ports:
        - containerPort: 7474 
          name: browser
        - containerPort: 7687
          name: bolt
        volumeMounts:
        - name: neo4j-persistent-storage
          mountPath: /data
      volumes:
      - name: neo4j-persistent-storage
        persistentVolumeClaim:
          claimName: neo4j-pv-claim


