apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkinsphp-deployment
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: jenkinsphp
    spec:
      containers:
      - name: jenkinsphp
        image: pblaas/jenkinsphp:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
          limits:
            cpu: "150m"
            memory: "128Mi"
        ports:
        - containerPort: 80
