apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locustslave
  namespace: loadtesting
  labels:
    app: locustslave
    tool: locust
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: locustslave
        tier: loadtesting
    spec:
      containers:
      - image: pblaas/locust-test
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        name: locustslave
        volumeMounts:
          - name: locustfile-config
            mountPath: /test
        env:
        - name: LOCUST_MODE
          value: slave
        - name: MASTER_HOST
          value: locustmaster
        - name: TARGET_URL
          value: http://yourtargetsite.ltd
      volumes:
        - name: locustfile-config
          configMap:
            name: locustfile
